apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: gateway
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: api-gateway
  namespaceSelector:
    matchNames:
      - gateway
  endpoints:
    - port: http       # the port name in Service
      path: /actuator/prometheus
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-api
  namespace: hello
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: hello-api
  namespaceSelector:
    matchNames:
      - hello
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
